server:
  servlet:
    context-path: /api/v1
  port: 8096

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://isabelle.db.elephantsql.com:5432/ylwvcdpb
    username: ylwvcdpb
    password: d1f7WLF0bolapN7vtdiZ9i9yJRXmFHP5


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
